SERVER_MAX_INFO_ONE_MESSAGE=10000
IVR_LANGUAGES=
IVR_DEFAULT_LANGUAGE=chinese
IVR_DEFAULT_ERROR_AUDIO=defaulterror
IVR_SETUP_TIMEOUT=20
IVR_RINGING_TIMEOUT=120
IVR_RTP_PORT=40000,47999
IVR_CODEC_PRIORITY=G729,G723,PCMA,PCMU,OPUS
IVR_ENABLE_PARSE_INBAND=false
IVR_ENABLE_PARSE_SECOND_INBAND=false
IVR_PARSE_DTMF_MODE=0
IVR_INPUT_TIMEOUT=5
IVR_TRACE_MASK=ERROR
IVR_TRACE_TO_SCREEN=false
IVR_TRACE_TO_FILE=true
IVR_TRACE_FILE_SIZE=40960
IVR_TRACE_CALL_FILE_SIZE=160
IVR_SOFTSWITCH_IP=
IVR_SOFTSWITCH_SIP_PORT=5060
IVR_SOFTSWITCH_AVAILABLE_IP=
IVR_SIP_RESEND_INTERVAL=3
IVR_SIP_SEND_RETRY=6
IVR_SIP_SESSION_RETRY=6
IVR_SIP_NO_TIMER_MAX_SESSION_TIME=7200
IVR_SIP_SESSION_TTL=600

IVR_CALL_REPORT_IP=
IVR_CALL_REPORT_PORT=8000
IVR_CALL_REPORT_RETRY=6
IVR_CALL_REPORT_RETRY_INTERVAL=3
IVR_ENABLE_CARD_LINE_RESTRICT=true
IVR_SHORTE164_AUTO_RECORD_ENABLE=false
IVR_SHORTE164_AUTO_RECORD_LENGTH=4
IVR_SHORTE164_AUTO_RECORD_MAX_NUMBER=5
IVR_CALLBACK_KEEP_LINE_TIME=30
IVR_CALLBACK_KEEP_LINE_RING_TIME=5
IVR_WEB_CALLBACK_SAME_TIME_CODEC=0
IVR_MEDIA_CHECK_TIME_OUT=2
IVR_IGNORE_CALLOUT_RTP_SECONDS=0
IVR_RESERVE_CALL_KEEP_TIME=300
